---
- name : add webupd8team/java ppa
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:webupd8team/java

- name : accept license...
  become: yes
  become_user: root
  with_items :
    - select
    - seen
  shell: >-
    echo debconf shared/accepted-oracle-license-v1-1 {{item}} true | debconf-set-selections
