---
java_ver : 8
java_minor_ver : 0
java_patch_ver: 131
java_post_patch_ver: b11

java_oracle_jre_uuid: d54c1d3a095b4ff2b6607d096fa80163 
java_oracle_jre_platform: linux-x64
java_oracle_jre_mirror: http://download.oracle.com/otn-pub/java/jdk
