---
java_oracle_jre_home: /usr/java/jre1.{{java_ver}}.{{java_minor_ver}}_{{java_patch_ver}}

java_oracle_jre_rpm: jre-{{java_ver}}u{{java_patch_ver}}-{{java_oracle_jre_platform}}.rpm

# http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jre-8u121-linux-x64.rpm
java_oracle_jre_url: '{{java_oracle_jre_mirror}}/{{java_ver}}u{{java_patch_ver}}-{{java_post_patch_ver}}/{{java_oracle_jre_uuid}}/{{java_oracle_jre_rpm}}'

java_oracle_jre_local_rpm: /tmp/{{java_oracle_jre_rpm}}

java_oracle_jre_setup: rpm

java_oracle_jre_pkgs:
  - '{{java_oracle_jre_local_rpm}}'
